version: '3.0'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  digital_currency_report:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - docker-compose.env
    environment:
      - DEBUG=true
    volumes:
      - ./pyproject.toml:/pyproject.toml
      - ./digital_currency_report:/digital_currency_report
    depends_on:
      - postgres