"""init_database

Revision ID: aa4cca647501
Revises: 
Create Date: 2021-03-03 10:59:33.328208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa4cca647501'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool',
    sa.Column('uuid', postgresql.UUID(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('last_modified', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_pool_name'), 'pool', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pool_name'), table_name='pool')
    op.drop_table('pool')
    # ### end Alembic commands ###
